package _27383Q1;

import java.time.LocalDate;
import java.util.Scanner;

public class Mainn {

    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);
        Inventory inventory = new Inventory(1, LocalDate.now(), LocalDate.now());
        int nextId = 2;

        System.out.println("\n=== STOCK MANAGEMENT SYSTEM (Q1) ID:27383 ===");

        boolean running = true;

        while (running) {

            System.out.println("\nMenu:");
            System.out.println("1 - Add Product");
            System.out.println("2 - Add Stock Item");
            System.out.println("3 - Record Purchase");
            System.out.println("4 - Record Sale");
            System.out.println("5 - Generate Report");
            System.out.println("0 - Exit");

            System.out.print("Choose option: ");
            String choice = sc.nextLine();

            try {

                switch (choice) {

                    case "1": // Add product
                        System.out.print("Product name: ");
                        String pname = sc.nextLine();

                        System.out.print("Unit price: ");
                        double price = Double.parseDouble(sc.nextLine());

                        System.out.print("Stock limit: ");
                        int limit = Integer.parseInt(sc.nextLine());

                        Product product = new Product(
                                nextId++, LocalDate.now(), LocalDate.now(),
                                pname, price, limit
                        );

                        System.out.println("Created: " + product + " | ID:27383");
                        break;

                    case "2": // Add stock item
                        System.out.print("Product name for stock item: ");
                        String prodName = sc.nextLine();

                        System.out.print("Unit price: ");
                        double uprice = Double.parseDouble(sc.nextLine());

                        Product prod = new Product(
                                nextId++, LocalDate.now(), LocalDate.now(),
                                prodName, uprice, 0
                        );

                        System.out.print("Quantity available: ");
                        int qty = Integer.parseInt(sc.nextLine());

                        System.out.print("Reorder level: ");
                        int reorder = Integer.parseInt(sc.nextLine());

                        StockItem si = new StockItem(
                                nextId++, LocalDate.now(), LocalDate.now(),
                                prod, qty, reorder
                        );

                        inventory.addStockItem(si);
                        System.out.println("Added stock item: " + si + " | ID:27383");
                        break;

                    case "3": // Purchase
                        System.out.print("Supplier name: ");
                        String sname = sc.nextLine();

                        Supplier sup = new Supplier(
                                nextId++, LocalDate.now(), LocalDate.now(),
                                sname, sname.replace(" ", "") + "@example.com",
                                "0780000000"
                        );

                        System.out.print("Purchase qty: ");
                        int pqty = Integer.parseInt(sc.nextLine());

                        Purchase purchase = new Purchase(
                                nextId++, LocalDate.now(), LocalDate.now(),
                                LocalDate.now(), pqty, sup
                        );

                        inventory.addPurchase(purchase);
                        System.out.println("Recorded purchase: " + purchase + " | ID:27383");
                        break;

                    case "4": // Sale
                        System.out.print("Customer name: ");
                        String cname = sc.nextLine();

                        System.out.print("Sold qty: ");
                        int sqty = Integer.parseInt(sc.nextLine());

                        Sale sale = new Sale(
                                nextId++, LocalDate.now(), LocalDate.now(),
                                LocalDate.now(), sqty, cname
                        );

                        inventory.addSale(sale);
                        System.out.println("Recorded sale: " + sale + " | ID:27383");
                        break;

                    case "5": // Report
                        StockReport report = new StockReport(
                                nextId++, LocalDate.now(), LocalDate.now(),
                                LocalDate.now(), "Generated by Mainn"
                        );

                        report.setInventory(inventory);
                        report.generateReport();

                        System.out.println("Report generated | ID:27383");
                        break;

                    case "0":
                        running = false;
                        break;

                    default:
                        System.out.println("Invalid option | ID:27383");
                }

            } catch (Exception ex) {
                System.out.println("Error: " + ex.getMessage());
            }
        }

        sc.close();
        System.out.println("Goodbye | ID:27383");
    }
}
